#version: '3.8'
#
#services:
#  app:
#    build: .
#    ports:
#      - "8080:8080"
#    depends_on:
#      - db
#    environment:
#      - DB_URL=jdbc:mysql://db:3306/HospitalDB
#      - DB_USER=root
#      - DB_PASSWORD=
#
#  db:
#    image: mysql:8
#    container_name: mysql-db
#    restart: always
#    environment:
#      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
#      MYSQL_DATABASE: HospitalDB
#      MYSQL_ROOT_PASSWORD: ""
#    ports:
#      - "3306:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#volumes:
#  mysql_data: